import type {Metadata} from 'next'
import {Source_Sans_3} from 'next/font/google'
import '@/lib/styles/globals.scss'
import Header from "@/app/header";
import PostJobInfo from "@/app/post-job-info/page";
import { Toaster } from 'react-hot-toast';


const mainFont = Source_Sans_3({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Prague morning jobs',
  description: 'Generated by create next app',
}

export default function PostJobInfoLayout({
                                    children,
                                  }: {
  children: React.ReactNode
}) {
  return (
    <>
    <Toaster/>
      <Header needBackgroundHeader={false} topHeaderTitle="" bottomHeaderTitle="Post a job"/>
      {children}
    </>
  )
}
