import type {Metadata} from 'next'
import {Source_Sans_3} from 'next/font/google'
import '@/lib/styles/globals.scss'
import Header from "@/app/header";
import Footer from "@/app/footer";
import PostJobInfo from "@/app/post-job-info/page";
import TopHeader from '@/lib/components/header/header';


const mainFont = Source_Sans_3({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Prague morning jobs',
  description: 'Generated by create next app',
}

export default function PostJobInfoLayout({
                                    children,
                                  }: {
  children: React.ReactNode
}) {
  return (
    <>
      <TopHeader/>
      {/*<Header topHeaderTitle="" bottomHeaderTitle="Post a job"/>*/}
      {children}
    </>
  )
}
