{
    length: 32,
    jobs: [
      {
        companyDetails: [Object],
        _id: '65a77c7ecf4f783aaff6a20c',
        id: 49,
        jobTitle: 'Designer',
        description: '<p><span style="color:rgb(127,135,158);"><strong>Describe the job in a good, easy-to-read format. Description is the key to encourage more applicants</strong></span></p>',
        jobUrl: 'https://prague-morning-app.vercel.app/',
        location: 'Yerevan',
        salary: '150000',
        currency: 'USD',
        salaryDetail: 'Month',
        workType: 'Onsite',
        education: 'High School',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1705475198879',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '65a77d18cf4f783aaff6a212',
        jobTitle: 'Designer',
        description: `<p><span style="background-color:rgb(255,255,255);color:rgb(127,135,158);">As a frontend product engineer, writing code and building beautiful user experiences is just one part of your job. You'll also talk to users, get involved with design, and develop your own opinion on what needs to exist in the world. Then you'll move with urgency to make it happen. To learn more about how we work, take a look at our Engineering Values. You'll work with a small engineering team to build mission-critical tools for creators. As one of our first engineers, you'll build entirely new products from scratch and make important architectural decisions. You'll be responsible for planning, organizing, and executing entire projects end to end, from idea to launch. To do so, you'll have to work closely with design, operations, and (of course) creators. You'll help build the foundation for Stir engineering standards, tooling, and processes. "Please be aware of the Fraud Company. The company will never be collecting any payment in the process of interview. Please immediately report to us if there's any companies that collecting payment to the Jofind."</span></p>`,
        jobUrl: 'https://prague-morning-app.vercel.app/',
        location: 'Moscow',
        salary: '200000',
        currency: 'EUR',
        salaryDetail: 'Week',
        workType: 'Onsite',
        education: 'Master',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1705475352226',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '65ce0e76d755e09b4f538996',
        jobTitle: 'Economist',
        description: '<p><span style="color:rgb(127,135,158);"><strong>Describe the job in a good, easy-to-read format. Description is the key to encourage more applicants</strong></span></p>',
        jobUrl: 'https://prague-morning-app.vercel.app/gsdffsdf',
        location: 'Yerevan',
        salary: '20000',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Onsite',
        education: 'Master',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1708002934368',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '65ce14edd3ae0bead111671b',
        jobTitle: 'Barber',
        description: '<p><strong>Job Description </strong><span style="color:rgb(224,79,51);"><strong>*</strong></span><strong>Describe the job in a good, easy-to-read format. Description is the key to encourage more applicants</strong></p>',
        jobUrl: 'https://prague-morning-app.vercel.app/',
        location: 'Prague',
        salary: '20000',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1708004589993',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '65ce175bd3ae0bead111673e',
        jobTitle: 'Policeman',
        description: '<p><strong>Job Description </strong><span style="color:rgb(224,79,51);"><strong>*</strong></span><strong>Describe the job in a good, easy-to-read format. Description is the key to encourage more applicants</strong></p>',
        jobUrl: 'https://prague-morning-app.vercel.app/',
        location: 'Madrid',
        salary: '20000',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Onsite',
        education: 'High School',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1708005211021',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '65d5f2fc2825cc502595e0b2',
        jobTitle: 'Farmer',
        description: `<p><span style="background-color:rgb(255,255,255);color:rgb(127,135,158);">As a frontend product engineer, writing code and building beautiful user experiences is just one part of your job. You'll also talk to users, get involved with design, and develop your own opinion on what needs to exist in the world. Then you'll move with urgency to make it happen. To learn more about how we work, take a look at our Engineering Values. You'll work with a small engineering team to build mission-critical tools for creators. As one of our first engineers, you'll build entirely new products from scratch and make important architectural decisions. You'll be responsible for planning, organizing, and executing entire projects end to end, from idea to launch. To do so, you'll have to work closely with design, operations, and (of course) creators. You'll help build the foundation for Stir engineering standards, tooling, and processes. "Please be aware of the Fraud Company. The company will never be collecting any payment in the process of interview. Please immediately report to us if there's any companies that collecting payment to the Jofind."</span></p>`,
        jobUrl: 'https://prague-morning-app.vercel.app/',
        location: 'Yerevan',
        salary: '2000',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Onsite',
        education: 'Master',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1708520188803',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '661f8ee4b6042f1a48de1ad0',
        jobTitle: 'Broker',
        description: 'Description for this job',
        jobUrl: 'https://prague-morning-app.vercel.app',
        location: 'Moscow',
        salary: '27000',
        currency: 'RUB',
        salaryDetail: 'Week',
        workType: 'Offsite',
        education: 'Bachelor’s dergee',
        jobTime: 'Full-Time(5 days)',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '661f8ee4b6042f1a48de1acf',
        jobTitle: 'Financier',
        description: 'Description for this job',
        jobUrl: 'https://prague-morning-app.vercel.app',
        location: 'Yerevan',
        salary: '5000',
        currency: 'USD',
        salaryDetail: 'Month',
        workType: 'Onsite',
        education: 'Master',
        jobTime: 'Full-Time(5 days)',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '661f8ee4b6042f1a48de1ad1',
        jobTitle: 'Manager',
        description: 'Description for this job',
        jobUrl: 'https://prague-morning-app.vercel.app',
        location: 'Kyiv',
        salary: '3000',
        currency: 'USD',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Bachelor’s dergee',
        jobTime: 'Full-Time(5 days)',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '6633a244c266a5f771ceffeb',
        jobTitle: 'WEb',
        description: '<p>s</p>',
        jobUrl: 'https://www.loom.com/share/2c11ae783ae24f9d9ca199f3ef1b4798?sid=5121b004-026d-431b-877d-a865d12f3081',
        location: 'Yerevan Armenia',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Offsite',
        education: 'High School',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1714659908688',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '6633a297c266a5f771ceffed',
        jobTitle: 'dsfgsdfgsd',
        description: '<p>dfs</p>',
        jobUrl: 'dfgsddffg',
        location: 'fgsdfgsdfg',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1714659991953',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '6653c91971518476f20331fc',
        jobTitle: 'Front-end developer',
        description: '<p>We are looking for an experienced Front-End developer to join our team.</p>',
        jobUrl: 'flagcdn.com',
        location: 'San Francisco',
        salary: '180000',
        currency: 'CZK',
        salaryDetail: 'Year',
        workType: 'Any',
        education: 'High School',
        jobTime: 'Half-Time(5 days)',
        advertisedDate: '1716767001154',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '6653d4bc31f6ce021eabb5b3',
        jobTitle: 'Programmer',
        description: '<p>dfgdfgfd</p>',
        jobUrl: 'https://www.linkedin.com/',
        location: 'fdgfdg',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1716769980863',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '669fad9996317ddd4a371b12',
        jobTitle: 'кцкцк',
        description: '<p>кцукуцкцу</p>',
        jobUrl: 'кцукцкц',
        location: 'цукц',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1721740697538',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a743656c86bad64b6008f9',
        jobTitle: 'web developer',
        description: '<p>courier for bolt</p>',
        jobUrl: 'praguemorning.cz',
        location: 'prague',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: null,
        jobTime: 'Any',
        advertisedDate: '1722237797810',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a8932d7a2949e981476274',
        jobTitle: 'Web dev',
        description: '<ul><li style="text-align:center;"><i><strong>hhadhxhxhsxhaxhsasxhxs</strong></i></li></ul>',
        jobUrl: 'instagram.com',
        location: 'Lviv',
        salary: '2000',
        currency: 'CZK',
        salaryDetail: 'Year',
        workType: 'Onsite',
        education: 'Master',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1722323757393',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a89688e489800edd15c1da',
        jobTitle: 'cdscds',
        description: '<p>dcscsd</p>',
        jobUrl: 'dcscsdsdc',
        location: 'cdsds',
        salary: '-44',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1722324616269',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a89b45505e8fb8d3962790',
        jobTitle: 'Webdev',
        description: '<ol><li style="text-align:center;"><i><strong>abcbcabcabcabac</strong></i></li></ol>',
        jobUrl: 'https://www.instagram.com/',
        location: 'Lviv',
        salary: '25000',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Onsite',
        education: 'Master',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1722325829196',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a89cd20a2cfce80db7ec2f',
        jobTitle: 'webdev',
        description: '<p>asfdasd</p>',
        jobUrl: 'instagram.com',
        location: 'lviv',
        salary: '2500',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Onsite',
        education: 'Master',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1722326226077',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a89d1e0a2cfce80db7ec31',
        jobTitle: 'wbdev',
        description: '<p>aaa</p>',
        jobUrl: 'instagram.com',
        location: 'lviv',
        salary: '2498',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1722326302773',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a89e833ec40a35e124c86a',
        jobTitle: 'as',
        description: '<p>as</p>',
        jobUrl: 'https://www.instagram.com/',
        location: 'lvi',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1722326659787',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a89f7a3ec40a35e124c86c',
        jobTitle: 'SAS',
        description: '<p>SA</p>',
        jobUrl: 'AS',
        location: 'SA',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1722326906675',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a8b1a81f8cdfc8288543f4',
        jobTitle: 'aa',
        description: '<p>aa</p>',
        jobUrl: 'aa',
        location: 'aa',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1722331560653',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a8b1cedbc5fa016a6cc155',
        jobTitle: 'aa7',
        description: '<p>aaa</p>',
        jobUrl: 'aa',
        location: 'aa',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1722331598641',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a8b255dbc5fa016a6cc159',
        jobTitle: 'job1',
        description: '<p>aa</p>',
        jobUrl: 'aa',
        location: 'aa',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1722331733466',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66a8b3361f8cdfc8288543fc',
        jobTitle: 'job2',
        description: '<p>aa</p>',
        jobUrl: 'aa',
        location: 'aa',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1722331958681',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66cf5d3836b93a0ff3dc78ed',
        jobTitle: 'something developer',
        description: '<p>smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething smoething&nbsp;</p>',
        jobUrl: 'https://www.figma.com/design/46deUwEkA8LYpgics3UQjD/Prague-Morning?node-id=0-1&t=oSTa7POpBOUOMzj7-0',
        location: 'nyc',
        salary: '2000',
        currency: 'USD',
        salaryDetail: 'Year',
        workType: 'Onsite',
        education: 'High School',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1724865848724',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66dba00455209a0e150f5428',
        jobTitle: 'something something',
        description: '<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>',
        jobUrl: 'https://nextjs.org/docs/app/building-your-application/optimizing/metadata',
        location: 'Paris',
        salary: '1000',
        currency: 'USD',
        salaryDetail: 'Year',
        workType: 'Onsite',
        education: 'Bachelor',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1725669380417',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66df4fef1a6b909af5661ae2',
        jobTitle: 'something',
        description: '<p>somethign somwthing somethign somwthingsomethign somwthingsomethign somwthingsomethign somwthingsomethign somwthingsomethign somwthing</p>',
        jobUrl: 'something.com',
        location: 'Berlin',
        salary: '1000',
        currency: 'USD',
        salaryDetail: 'Month',
        workType: 'Onsite',
        education: 'PhD',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1725911023291',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66e3277ab564c79abcb6a667',
        jobTitle: 'something dev',
        description: '<p>somewthing somthing somewthing somthing somewthing somthing somewthing somthing somewthing somthing somewthing somthing&nbsp;</p>',
        jobUrl: 'google.com',
        location: 'texas',
        salary: '1000',
        currency: 'USD',
        salaryDetail: 'Month',
        workType: 'Offsite',
        education: 'Coursework',
        jobTime: 'Full-Time(5 days)',
        advertisedDate: '1726162810009',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '66eac5f7c7af0cc842152c14',
        jobTitle: 'developer',
        description: '<p>hellop</p>',
        jobUrl: 'expedia.it',
        location: 'prague ',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Any',
        education: 'Master',
        jobTime: 'Any',
        advertisedDate: '1726662135108',
        __v: 0
      },
      {
        companyDetails: [Object],
        _id: '670bde4805c3f6a7367f8681',
        jobTitle: 'developer',
        description: '<p>hello</p>',
        jobUrl: 'expedia.com',
        location: 'prague',
        currency: 'CZK',
        salaryDetail: 'Month',
        workType: 'Onsite',
        education: 'Master',
        jobTime: 'Half-Time(5 days)',
        advertisedDate: '1728831048267',
        __v: 0
      }
    ]
  }