import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "@/lib/styles/globals.scss";
import Header from "@/app/header";
import ClientProvider from "@/lib/components/ClientProvider";


const mainFont = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Joobly | Packages",
	description: "Generated by create next app",
};

export default function PackagesLayout({ children }: { children: React.ReactNode }) {
	return (
		<>
			<Header
				extraBottomHeader='Simple pricing. No surprise fees. Advanced features.'
				topHeaderTitle=''
				bottomHeaderTitle='Packages and Subscriptions'
			/>
			<ClientProvider>
					{children}
			</ClientProvider>
			
		</>
	);
}
