import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "@/lib/styles/globals.scss";
import TopHeader from "@/lib/components/header/header";


const mainFont = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Joobly | Contact Us",
	description: "Generated by create next app",
};

export default function JobLayout({ children }: { children: React.ReactNode }) {
	return (
		<>
              <TopHeader />
              <div className='header-background-line hidden lg:block'></div>
			{children}
		</>
	);
}
