import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "@/lib/styles/globals.scss";
import Header from "../header";

import { Toaster } from 'react-hot-toast';

const mainFont = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Joobly | Contact Us",
	description: "Generated by create next app",
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
	return (
		<>
		 <Toaster/>
              <Header needBackgroundHeader={true} topHeaderTitle='' bottomHeaderTitle='Welcome!'/>
			{children}
		</>
	);
}
